name: Game issues
description: Create a bug report to help us improve.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out a bug report. Remember to fill out all fields including the title above. 
        An issue that is not properly filled out will be closed. 
  - type: textarea
    id: current
    attributes:
      label: Current Behaviour
      description: |
        Description of the problem or issue here.
        Include entries of affected creatures / items / quests / spells etc.
        Never upload files! Use GIST for text and YouTube for videos!
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: |
        Tell us what should happen instead.
    validations:
      required: true
  - type: textarea
    id: source
    attributes:
      label: Source
      description: |
        If you have a source that proves how it is supposed to work, please add that to make it easier for devs to fix the issue.
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the problem
      description: |
        What does someone else need to do to encounter the same bug?
      placeholder: |
        1. Step 1
        2. Step 2
        3. Step 3
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Extra Notes
      description: |
        Do you have any extra notes that can help solve the issue that does not fit any other field?
      placeholder: |
        None
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thank you for your contribution.
