name: Bug report
description: Use this form to report a bug.
title: "[BUG] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill in the required fields below.

  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behaviour
      description: Describe the problem or issue here.
      placeholder: "Describe what is happening now..."
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behaviour
      description: Tell us what should happen instead.
      placeholder: "Describe the expected behaviour..."
      required: true

  - type: input
    id: source
    attributes:
      label: Source (optional)
      description: If you have a source, add a link.
      placeholder: "URL or description"
    validations:
      required: false

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Explain how to reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
      required: true

  - type: textarea
    id: extra_notes
    attributes:
      label: Extra Notes
      description: Anything else that may help.
      placeholder: "Optional notes..."
      required: false
